force-app/main/default/objects/Volunteer_Hours__c/Volunteer_Hours__c.object-meta.xml
<CustomObject>
    <label>Volunteer Hours</label>
    <nameField>
        <displayFormat>VH {00000000}</displayFormat>
        <label>VH No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Hours__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Volunteer Hours</relationshipLabel>
    <relationshipName>Volunteer_Hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Hours__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.Volunteer_Status__c</field>
            <operation>equals</operation>
            <value>Application, Prospective, Pending - Active, Active</value>
        </filterItems>
        <infoMessage>Defaults to Contacts with Status = Application, Prospective, Pending - Active, Active</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Hours</relationshipLabel>
    <relationshipName>Volunteer_Hours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Hours__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Class Assisting</fullName>
                <default>true</default>
                <label>Class Assisting</label>
            </value>
            <value>
                <fullName>Class Setup</fullName>
            </value>
            <value>
                <fullName>Morning Tea</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Fundraising</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Wigs</fullName>
            </value>
            <value>
                <fullName>Stock</fullName>
            </value>
            <value>
                <fullName>Photographer</fullName>
            </value>
            <value>
                <fullName>Volunteer Observer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Hours__c/fields/Volunteer_Hours__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Hours__c</fullName>
    <defaultValue>3</defaultValue>
    <inlineHelpText>This will default to 3 if left blank on creation</inlineHelpText>
    <label>Volunteer Hours</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer_Hours__c/fields/Volunteer_Status__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Status__c</fullName>
    <label>Volunteer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Stood Down</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Day Off</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VolunteerListControllerTest.cls
@IsTest
public class VolunteerListControllerTest {
    static testmethod void testVolunteerList(){
        Campaign campaign = new Campaign(Name = 'TEst', StartDate = system.today(), IsActive = true, Status = 'In Progress');
        insert campaign;
        Account acct = new Account (Name = 'Test Account', Category__c = 'Other', Type = 'Corporate');
        insert acct;
        Contact con = new Contact (FirstName = 'test', LastName = 'Test', Category__c = 'Other', AccountId = acct.Id);
        insert con;
        CampaignMember cm = new CampaignMember(ContactId = con.Id, CampaignID = campaign.Id, Status = 'Completed');
        insert cm;
        Volunteer_Hours__c vh = new Volunteer_Hours__c();
        vh.Campaign__c = campaign.Id;
        vh.Contact__c = con.Id;
        // vh.Role__c = 'Class Assisting'; 
        vh.Volunteer_Status__c = 'Interested';
        insert vh;
        
        ApexPages.StandardController stdCon = new ApexPages.StandardController(campaign);
        VolunteerListController cont = new VolunteerListController(stdCon);
        List<Volunteer_Hours__c> vList = cont.volunteerHoursList;
        cont.saveDetails();
    }
}